### ISSUE TITLE
[FEAT] 글 쓰기 화면 만들기

### ISSUE THREAD

**Issue by stev3j** [TW00D/letsgo-mobile-mini#18]
## 어떤 기능입니까?
글쓰기 화면

## TODO
- [x] 댓글 작성 화면 만들기
- [x] 게시물 작성 기능 만들기
- [x] 댓글 작성 기능 만들기
- [ ] 사진 포스팅 기능 만들기
- [ ] 게시물 & 댓글 에러링하기
